apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dotnet-github-actions-110425
  janus-idp.io/tekton: dotnet-github-actions-110425
  backstage.io/kubernetes-id: dotnet-github-actions-110425
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet-github-actions-110425
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
